name: ff-three-infra
description: ForgeFabrik Academy AWS infrastructure
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
