//! Goal system — GOAP-style goal stack with preconditions.
//!
//! Goals are pure data. The `Planner` (TODO 3) selects and sequences them.
//! Goal evaluation (`is_met`) uses only character state — no I/O.

use serde::{Deserialize, Serialize};

use types::{CharacterId, GoalId, LocationId, WorldTick};

/// Maximum number of goals a character can hold simultaneously.
pub const MAX_GOALS: usize = 16;

/// A single goal on the character's goal stack.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Goal {
    pub id:            GoalId,
    pub kind:          GoalType,
    /// Higher value = higher urgency. Range: 0..100.
    pub priority:      i32,
    /// All preconditions must be met before this goal can be activated.
    pub preconditions: Vec<Condition>,
    /// Optional deadline — goal is abandoned if not started by this tick.
    pub deadline:      Option<WorldTick>,
    pub created_at:    WorldTick,
}

impl Goal {
    pub fn new(kind: GoalType, priority: i32, at: WorldTick) -> Self {
        Self {
            id: GoalId::new(),
            kind,
            priority: priority.clamp(0, 100),
            preconditions: vec![],
            deadline: None,
            created_at: at,
        }
    }

    pub fn with_preconditions(mut self, conds: Vec<Condition>) -> Self {
        self.preconditions = conds;
        self
    }

    pub fn with_deadline(mut self, deadline: WorldTick) -> Self {
        self.deadline = Some(deadline);
        self
    }

    /// `true` when all preconditions are satisfied.
    pub fn preconditions_met(&self, stats: &crate::stats::Stats) -> bool {
        self.preconditions.iter().all(|c| c.is_met(stats))
    }

    /// `true` when the deadline has passed.
    pub fn is_expired(&self, current_tick: WorldTick) -> bool {
        self.deadline.map(|d| current_tick > d).unwrap_or(false)
    }
}

/// What the character wants to achieve.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum GoalType {
    // ── Basic needs ───────────────────────────────────────────────────────────
    Eat,
    Sleep,
    Rest,
    RecoverHealth,

    // ── Social ────────────────────────────────────────────────────────────────
    ConversationWith(CharacterId),
    BuildRelationship { with: CharacterId, target_trust: f32 },
    JoinFaction(types::FactionId),

    // ── Movement ──────────────────────────────────────────────────────────────
    TravelTo(LocationId),

    // ── Work ──────────────────────────────────────────────────────────────────
    Work,

    // ── Quest integration ─────────────────────────────────────────────────────
    CompleteQuest(String),

    // ── LLM boundary ─────────────────────────────────────────────────────────
    /// Goal text generated by runtime/agents via LLM.
    /// The domain handles it uniformly; LLM fills in the text.
    Custom(String),
}

impl GoalType {
    pub fn display_name(&self) -> &str {
        match self {
            Self::Eat                  => "eat",
            Self::Sleep                => "sleep",
            Self::Rest                 => "rest",
            Self::RecoverHealth        => "recover_health",
            Self::Work                 => "work",
            Self::TravelTo(_)          => "travel",
            Self::ConversationWith(_)  => "converse",
            Self::BuildRelationship{..}=> "build_relationship",
            Self::JoinFaction(_)       => "join_faction",
            Self::CompleteQuest(_)     => "complete_quest",
            Self::Custom(_)            => "custom",
        }
    }
}

/// A precondition that must be satisfied before a goal can be activated.
///
/// Evaluated against `Stats` only — no I/O, no randomness.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Condition {
    EnergyAtLeast(i32),
    HealthAtLeast(i32),
    NotHungry,
    NotTired,
    TickAfter(WorldTick),
}

impl Condition {
    /// Check whether this condition is currently satisfied.
    ///
    /// Pure function — deterministic, no side effects.
    pub fn is_met(&self, stats: &crate::stats::Stats) -> bool {
        match self {
            Self::EnergyAtLeast(min) => stats.energy >= *min,
            Self::HealthAtLeast(min) => stats.health >= *min,
            Self::NotHungry          => !stats.is_hungry(),
            Self::NotTired           => !stats.is_tired(),
            Self::TickAfter(_)       => true, // tick check handled by planner
        }
    }
}

/// The character's goal stack.
///
/// Invariant: `pending` is kept sorted by priority descending after mutation.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GoalStack {
    /// The goal currently being executed (if any).
    pub active:  Option<Goal>,
    /// Queued goals, highest priority first.
    pub pending: Vec<Goal>,
}

impl GoalStack {
    /// Add a goal and re-sort.
    /// Returns `Err` if the stack is full.
    pub fn push(&mut self, goal: Goal) -> Result<(), crate::errors::CharacterError> {
        if self.pending.len() >= MAX_GOALS {
            return Err(crate::errors::CharacterError::GoalStackOverflow { max: MAX_GOALS });
        }
        self.pending.push(goal);
        self.sort();
        Ok(())
    }

    /// Remove a goal by ID from either the active slot or the pending queue.
    pub fn remove(&mut self, id: GoalId) {
        if self.active.as_ref().map(|g| g.id) == Some(id) {
            self.active = None;
        }
        self.pending.retain(|g| g.id != id);
    }

    /// Select and activate the highest-priority goal whose preconditions are met.
    pub fn activate_next(&mut self, stats: &crate::stats::Stats, current_tick: WorldTick) {
        if self.active.is_some() { return; }
        // Expire overdue goals first.
        self.pending.retain(|g| !g.is_expired(current_tick));
        // Pick first goal whose preconditions are met.
        if let Some(pos) = self.pending.iter().position(|g| g.preconditions_met(stats)) {
            self.active = Some(self.pending.remove(pos));
        }
    }

    pub fn is_empty(&self) -> bool { self.active.is_none() && self.pending.is_empty() }

    fn sort(&mut self) {
        self.pending.sort_by(|a, b| b.priority.cmp(&a.priority));
    }
}
