//! Character memory — curated subset of observed WorldEvents.
//!
//! Memory is NOT the full world log. It is a character's *interpretation*
//! of events, weighted by emotional impact.
//!
//! Decay is deterministic: weight -= elapsed_ticks * DECAY_RATE.
//! No RNG. Replay-safe.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use types::{EpisodeId, WorldTick};

/// How fast emotional weight fades per simulation tick.
pub const DECAY_RATE_PER_TICK: f32 = 0.00005;

/// Episodes below this weight are considered forgotten.
pub const FORGET_THRESHOLD: f32 = 0.05;

/// A curated record of one observed event in the character's memory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Episode {
    pub id:          EpisodeId,
    /// Human-readable summary of the event (generated by the runtime/LLM layer).
    pub summary:     String,
    /// Emotional weight 0.0 (forgotten) → 1.0 (vivid).
    pub weight:      f32,
    pub observed_at: WorldTick,
    pub forgotten:   bool,
}

impl Episode {
    pub fn new(id: EpisodeId, summary: impl Into<String>, weight: f32, at: WorldTick) -> Self {
        Self {
            id,
            summary: summary.into(),
            weight: weight.clamp(0.0, 1.0),
            observed_at: at,
            forgotten: false,
        }
    }

    /// Apply deterministic decay based on elapsed ticks.
    ///
    /// Call this inside the `MemoryDecayApplied` reducer branch.
    /// Must be called with the SAME `current_tick` for replay to be correct.
    pub fn decay(&mut self, current_tick: WorldTick) {
        let elapsed = current_tick.0.saturating_sub(self.observed_at.0);
        let decay   = elapsed as f32 * DECAY_RATE_PER_TICK;
        self.weight = (self.weight - decay).max(0.0);
        if self.weight < FORGET_THRESHOLD {
            self.forgotten = true;
        }
    }
}

/// A factual belief held by the character ("the baker is friendly").
///
/// Beliefs persist longer than episodes and are updated by reflection events.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Belief {
    pub content:    String,
    /// Subjective confidence 0.0–1.0.
    pub confidence: f32,
    pub formed_at:  WorldTick,
}

/// All stored experiences and beliefs for one character.
///
/// `episodes` is a curated subset of observed WorldEvents.
/// `beliefs`  is a distilled knowledge base derived from reflection.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Memory {
    pub episodes: Vec<Episode>,
    /// Key: topic (e.g. "faction:merchants", "person:alice", "location:tavern").
    pub beliefs: BTreeMap<String, Belief>,
}

impl Memory {
    /// Add an episode; cap memory at `max_episodes` by dropping the
    /// lowest-weight entries (deterministic; no RNG).
    pub fn record(&mut self, episode: Episode, max_episodes: usize) {
        self.episodes.push(episode);
        if self.episodes.len() > max_episodes {
            // Sort ascending by weight, remove the weakest.
            self.episodes.sort_by(|a, b| {
                a.weight.partial_cmp(&b.weight).unwrap_or(std::cmp::Ordering::Equal)
            });
            self.episodes.remove(0);
        }
    }

    /// Apply decay to all episodes and remove forgotten ones.
    pub fn apply_decay(&mut self, current_tick: WorldTick) {
        for ep in &mut self.episodes {
            ep.decay(current_tick);
        }
        self.episodes.retain(|ep| !ep.forgotten);
    }

    /// Return episodes above a weight threshold, sorted by weight descending.
    pub fn salient(&self, threshold: f32) -> Vec<&Episode> {
        let mut result: Vec<&Episode> = self.episodes.iter()
            .filter(|e| !e.forgotten && e.weight >= threshold)
            .collect();
        result.sort_by(|a, b| b.weight.partial_cmp(&a.weight).unwrap_or(std::cmp::Ordering::Equal));
        result
    }
}
